# Generated by Django 4.2.23 on 2026-10-10 00:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handy', '0032_trust_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_min_certifications', models.PositiveSmallIntegerField(default=1, verbose_name='Justificatifs professionnels approuvés (min.)')),
                ('expert_min_completed', models.PositiveIntegerField(default=10, verbose_name='Missions terminées (min.)')),
                ('expert_min_reviews', models.PositiveIntegerField(default=5, verbose_name='Avis clients retenus (min.)')),
                ('expert_min_rating', models.FloatField(default=4.3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne (min. /5)')),
                ('expert_min_experience_years', models.PositiveSmallIntegerField(default=2, verbose_name="Années d'expérience déclarées (min.)")),
                ('sure_min_completed', models.PositiveIntegerField(default=15, verbose_name='Missions terminées sur la période (min.)')),
                ('sure_min_punctuality', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Taux de ponctualité (min.)')),
                ('sure_min_punctuality_sample', models.PositiveIntegerField(default=10, verbose_name='Missions mesurées pour la ponctualité (min.)')),
                ('sure_max_dispute_rate', models.FloatField(default=0.05, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Taux de litiges (max.)')),
                ('sure_min_rating', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne (min. /5)')),
                ('sure_min_reviews', models.PositiveIntegerField(default=5, verbose_name='Avis clients retenus (min.)')),
                ('sure_window_days', models.PositiveIntegerField(default=365, verbose_name="Période d'observation (jours)")),
                ('punctuality_tolerance_minutes', models.PositiveSmallIntegerField(default=15, verbose_name="Tolérance de ponctualité (minutes après l'heure prévue)")),
                ('min_sample', models.PositiveSmallIntegerField(default=3, verbose_name="Échantillon minimal pour qu'une mesure compte dans le score")),
                ('reevaluation_hours', models.PositiveSmallIntegerField(default=24, verbose_name='Réévaluation périodique (heures)')),
                ('weight_identity', models.PositiveSmallIntegerField(default=25, verbose_name='Poids : identité vérifiée (KYC)')),
                ('weight_satisfaction', models.PositiveSmallIntegerField(default=30, verbose_name='Poids : satisfaction clients')),
                ('weight_reliability', models.PositiveSmallIntegerField(default=20, verbose_name='Poids : fiabilité (ponctualité, litiges)')),
                ('weight_reactivity', models.PositiveSmallIntegerField(default=10, verbose_name='Poids : réactivité')),
                ('weight_track_record', models.PositiveSmallIntegerField(default=10, verbose_name='Poids : missions terminées')),
                ('weight_certifications', models.PositiveSmallIntegerField(default=5, verbose_name='Poids : justificatifs professionnels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Critères Tratra Trust',
                'verbose_name_plural': 'Critères Tratra Trust',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(db_index=True, max_length=60)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('organization_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('VERIFIE', 'Vérifié'), ('EXPERT', 'Expert'), ('SUR', 'Sûr')], db_index=True, max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_reason', models.TextField(blank=True, default='')),
                ('end_reason', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='handy.handymanprofile')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['profile', 'ended_at'], name='trust_badge_profile_684696_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='badgeaward',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('profile', 'code'), name='trust_one_active_badge_per_code'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='trust_audit_target__ef76a6_idx'),
        ),
    ]
