# Generated by Django 4.2.23 on 2026-10-10 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0032_trust_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_id', to='handy.handymanprofile')),
            ],
            options={
                'verbose_name': 'Tratra ID',
                'verbose_name_plural': 'Tratra ID',
            },
        ),
        migrations.CreateModel(
            name='IdentityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_checks', to='handy.booking')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='trust.professionalid')),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['booking', '-verified_at'], name='trust_ident_booking_850c1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_passes', to='handy.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['booking', '-created_at'], name='trust_booki_booking_ba701f_idx')],
            },
        ),
    ]
