#/Users/ogahserge/Documents/tratra/docker-compose.yml
# docker-compose.yml (stack de l’app tratra — sans Traefik)
# Traefik tourne dans un autre compose et expose 80/443
# Assure-toi que le réseau externe "proxy" existe:  docker network ls | grep proxy || docker network create proxy

networks:
  web:          # réseau interne de l’app
    driver: bridge
  proxy:        # réseau partagé avec Traefik (externe)
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:
  minio_data: { }

services:
  # --- Base de données Postgres + PostGIS ---
  tratradb:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [web]
    restart: unless-stopped
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web
    networks:
      - web
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # ⚠️ Évite de réutiliser le même host que l’app.
      # Donne un host dédié à l’API S3 et à la console
      - traefik.http.routers.minio-api.rule=Host(`minio.tratra.net`)
      - traefik.http.routers.minio-api.entrypoints=websecure
      - traefik.http.routers.minio-api.tls.certresolver=lets
      - traefik.http.services.minio-api.loadbalancer.server.port=9000

      - traefik.http.routers.minio-console.rule=Host(`console.tratra.net`)
      - traefik.http.routers.minio-console.entrypoints=websecure
      - traefik.http.routers.minio-console.tls.certresolver=lets
      - traefik.http.services.minio-console.loadbalancer.server.port=9001

  # --- Redis (broker Celery + cache + Channels) ---
  redis:
    image: redis:7
    command: ["redis-server","--save","","--appendonly","no"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [web]
    restart: unless-stopped

  # --- tratraweb Django/ASGI (Daphne) ---
  tratraweb:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # Entrypoint qui fait: check DB/Redis, migrate, collectstatic… puis Daphne
    command: ["/app/docker/entrypoint.sh", "daphne", "-b", "0.0.0.0", "-p", "8000", "tratra.asgi:application"]
    depends_on:
      tratradb:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Labels Traefik: route HTTPS -> service tratraweb:8000
    labels:
      - traefik.enable=true
      # Traefik doit utiliser le réseau "proxy"
      - traefik.docker.network=proxy
      - traefik.http.routers.tratraweb.rule=Host(`tratra.net`)


      # Router provisoire en clair sur 1934
#      - traefik.http.routers.tratraweb-1934.rule=Host(`${tratraweb_HOST}`)
#      - traefik.http.routers.tratraweb-1934.entrypoints=debug1934
#      - traefik.http.routers.tratraweb-1934.tls=true
#      - traefik.http.routers.tratraweb-1934.tls.certresolver=lets
#      - traefik.http.routers.tratraweb-1934.service=tratraweb-svc
      # Router unique pour l’app
      - traefik.http.routers.tratraweb-app.rule=Host(`${tratraweb_HOST}`)
      - traefik.http.routers.tratraweb-app.entrypoints=websecure
      - traefik.http.routers.tratraweb-app.tls.certresolver=lets
#       Chaîne de middlewares (renommée pour éviter toute collision de noms globaux)
      - traefik.http.routers.tratraweb-app.middlewares=tratraweb-sec-headers@docker,tratraweb-compress@docker,tratraweb-rl@docker

      # Service séparé (nom explicite)
      - traefik.http.services.tratraweb-svc.loadbalancer.server.port=8000

      # Middlewares (noms préfixés "tratraweb-")
      - traefik.http.middlewares.tratraweb-sec-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.tratraweb-sec-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.tratraweb-sec-headers.headers.stsPreload=true
      - traefik.http.middlewares.tratraweb-sec-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.tratraweb-sec-headers.headers.frameDeny=true
      - traefik.http.middlewares.tratraweb-sec-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.tratraweb-compress.compress=true
      - traefik.http.middlewares.tratraweb-rl.ratelimit.average=150
      - traefik.http.middlewares.tratraweb-rl.ratelimit.burst=250

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - web     # parle à db/redis
      - proxy   # exposé à Traefik
    restart: unless-stopped

  # --- Celery Worker ---
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A tratra worker -l info --prefetch-multiplier=1 --max-tasks-per-child=200 --queues=default,notifications
    depends_on:
      tratradb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [web]
    restart: unless-stopped

  # --- Celery Beat (planificateur) ---
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A tratra beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      tratradb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [web]
    restart: unless-stopped
