# settings/base.py
"""
Django settings for tratra project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import channels
import environ
from decouple import config
from django.core.exceptions import ImproperlyConfigured
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration

from tratra.settings import env


def env_bool(name, default=False):
    """Read a boolean environment setting without accepting a truthy string."""
    value = config(name, default=str(default))
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    return [item.strip() for item in config(name, default=default).split(",") if item.strip()]


def required_env(name):
    value = config(name, default="").strip()
    if not value:
        raise ImproperlyConfigured(f"{name} must be configured when object storage is enabled.")
    return value


# env = environ.Env()
# environ.Env.read_env()
DEBUG = env_bool("DEBUG", False)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
# A local-only fallback keeps isolated tests bootable.  prod.py rejects it.
SECRET_KEY = config('SECRET_KEY', default='django-insecure-local-development-key-change-me')

# Allow developers and non-standard production images to point Django GIS at
# their installed libraries.  When absent, Django performs its normal
# auto-discovery (the container and CI image install the system packages).
if os.getenv('GDAL_LIBRARY_PATH'):
    GDAL_LIBRARY_PATH = os.environ['GDAL_LIBRARY_PATH']
if os.getenv('GEOS_LIBRARY_PATH'):
    GEOS_LIBRARY_PATH = os.environ['GEOS_LIBRARY_PATH']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-98yp&99d&^j57y15a7!*3h4+t#d2z0r@+e!@dy=e*_b(9m!47i'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    "tratra.net,www.tratra.net,tratra.ci,www.tratra.ci,127.0.0.1,localhost,tratraweb",
)

# Pendant l’accès provisoire en HTTP sur :1934, ne force pas HTTPS

# CSRF (pas strictement nécessaire pour /admin en même origine, mais utile si tu postes depuis un front)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'handy',
    'trust',
    # Libs
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.linkedin',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    'axes',
    'django_celery_beat',
    'storages',
    'django_cleanup',
    'simple_history',
    'actstream',
    'channels',
    'push_notifications',
    'djstripe',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'tailwind',
    'theme',
    'grappelli',
    'import_export',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'django.contrib.humanize',

]
INSTALLED_APPS += ["corsheaders"]

# CORS : whitelist d'origines, pilotée par env. `*` désactivé par défaut.
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", False)
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "https://tratra.net,https://www.tratra.net,https://tratra.ci,https://www.tratra.ci,"
    "http://localhost:3000,http://127.0.0.1:3000",
)
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'axes.middleware.AxesMiddleware',
    'handy.middleware.IPBlacklistMiddleware',

]

ROOT_URLCONF = 'tratra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tratra.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = 'handydash'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
# ACCOUNT_USERNAME_REQUIRED = False  # Ne pas exiger le champ username
# django-allauth 65+ uses ACCOUNT_LOGIN_METHODS.  Keep both username and email
# accepted without relying on the deprecated ACCOUNT_AUTHENTICATION_METHOD.
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True  # Empêche les doublons

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # ✅ plus de SessionAuthentication
    ),
    # Sécurisé par défaut : il faut être authentifié. Les endpoints publics
    # (inscription, /nearby, /price-estimate, /slides) déclarent AllowAny explicitement.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Erreurs codées {code, detail, fields} (D13) ; les autres erreurs DRF gardent
    # leur format historique (handy/api/errors.py).
    'EXCEPTION_HANDLER': 'handy.api.errors.exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON', default='60/min'),
        'user': config('THROTTLE_USER', default='1000/hour'),
        'login': config('THROTTLE_LOGIN', default='10/min'),
        'recovery': config('THROTTLE_RECOVERY', default='20/hour'),
        'webhook': config('THROTTLE_WEBHOOK', default='120/min'),
    },
}

# === OpenAPI / Swagger (drf-spectacular) — découplage SPA ===
SPECTACULAR_SETTINGS = {
    'TITLE': 'Tratra API',
    'DESCRIPTION': "API de la marketplace de services à domicile Tratra (clients, artisans, entreprises).",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Doc consultable pour le dev frontend ; restreindre en prod si besoin.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SCHEMA_PATH_PREFIX': r'/handy',
}

# === JWT (durci) ===
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

USE_I18N = True
TIME_ZONE = 'Africa/Abidjan'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
from decouple import config
import os

# ---------- STATIC & MEDIA ----------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

if DEBUG:
    # Assurez-vous que whitenoise est correctement configuré
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

    # Configuration pour servir les fichiers média en développement
    from django.conf.urls.static import static

    urlpatterns = [] + static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

# === PRIVATE OBJECT STORAGE ===
# Object storage is opt-in.  In particular, a fresh environment must never
# silently connect to a MinIO instance with known default credentials.
MINIO_ENABLED = env_bool('MINIO_ENABLED', False)
KYC_MAX_UPLOAD_BYTES = int(config('KYC_MAX_UPLOAD_BYTES', default='10485760'))
KYC_ALLOWED_CONTENT_TYPES = tuple(env_list(
    'KYC_ALLOWED_CONTENT_TYPES',
    'application/pdf,image/jpeg,image/png',
))
KYC_SIGNED_URL_TTL_SECONDS = int(config('KYC_SIGNED_URL_TTL_SECONDS', default='300'))
# Médias publics (photos d'artisans, images de services) : TTL de signature distinct
# du KYC. Les pages publiques sont mises en cache (ISR, revalidate 300 s) : un TTL
# de 300 s y figerait des URL déjà expirées (403). 604800 s = maximum SigV4.
MEDIA_SIGNED_URL_TTL_SECONDS = int(config('MEDIA_SIGNED_URL_TTL_SECONDS', default='604800'))
if KYC_MAX_UPLOAD_BYTES <= 0:
    raise ImproperlyConfigured('KYC_MAX_UPLOAD_BYTES must be greater than zero.')
if not KYC_ALLOWED_CONTENT_TYPES:
    raise ImproperlyConfigured('KYC_ALLOWED_CONTENT_TYPES must contain at least one content type.')
if not 60 <= KYC_SIGNED_URL_TTL_SECONDS <= 3600:
    raise ImproperlyConfigured('KYC_SIGNED_URL_TTL_SECONDS must be between 60 and 3600 seconds.')
if not 3600 <= MEDIA_SIGNED_URL_TTL_SECONDS <= 604800:
    raise ImproperlyConfigured('MEDIA_SIGNED_URL_TTL_SECONDS must be between 3600 and 604800 seconds.')

if MINIO_ENABLED:
    KYC_STORAGE_BUCKET_NAME = required_env('KYC_STORAGE_BUCKET_NAME')
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "private_kyc": {
            "BACKEND": "handy.storage.PrivateKycS3Storage",
            "OPTIONS": {
                "bucket_name": KYC_STORAGE_BUCKET_NAME,
                "querystring_auth": True,
                "querystring_expire": KYC_SIGNED_URL_TTL_SECONDS,
                "default_acl": None,
                "file_overwrite": False,
                "object_parameters": {"CacheControl": "private, no-store, max-age=0"},
            },
        },
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

    # No MinIO/AWS credentials, bucket, or endpoint has an insecure fallback.
    AWS_ACCESS_KEY_ID = required_env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = required_env('AWS_SECRET_ACCESS_KEY')

    # MinIO / S3 configuration
    AWS_STORAGE_BUCKET_NAME = required_env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = required_env('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')

    # URL settings
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_VERIFY = env_bool('AWS_S3_VERIFY', True)

    # Keep all user uploads private by default.  A custom S3 domain bypasses
    # django-storages' presigning path, so it is deliberately unset here.
    AWS_S3_CUSTOM_DOMAIN = None
    AWS_QUERYSTRING_AUTH = True
    # Stockage "default" (médias publics) uniquement : "private_kyc" fixe son propre
    # querystring_expire = KYC_SIGNED_URL_TTL_SECONDS dans ses OPTIONS ci-dessus.
    AWS_QUERYSTRING_EXPIRE = MEDIA_SIGNED_URL_TTL_SECONDS
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'private, max-age=300',
    }

else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "private_kyc": {
            "BACKEND": "handy.storage.PrivateKycFileSystemStorage",
            "OPTIONS": {"location": BASE_DIR / "private_kyc"},
        },
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# Hôtes autorisés pour Service.image_url (https uniquement, §4.7) : le stockage
# public du projet. Par défaut, l'hôte de AWS_S3_ENDPOINT_URL (MinIO) ; en dev sans
# MinIO, localhost. Toute autre URL est refusée (400 invalid_image_url).
if MINIO_ENABLED:
    from urllib.parse import urlsplit as _urlsplit
    _default_media_hosts = _urlsplit(AWS_S3_ENDPOINT_URL).hostname or ''
else:
    _default_media_hosts = 'localhost,127.0.0.1'
MEDIA_PUBLIC_HOSTS = [
    h.lower() for h in (env_list('MEDIA_PUBLIC_HOSTS') or _default_media_hosts.split(',')) if h
]

WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365
# Tolère un manifeste statique incomplet (tests/dev sans collectstatic récent) :
# {% static %} renvoie le chemin brut au lieu de lever une erreur.
WHITENOISE_MANIFEST_STRICT = False
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'handy.User'  # Remplacez 'handy' par le nom de votre app

# === CHANNELS ===
ASGI_APPLICATION = 'tratra.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(config('REDIS_HOST', default='redis'), 6379)],
        },
    },
}

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']
# === CELERY ===
CELERY_BROKER_URL = config('REDIS_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_BEAT_SCHEDULE = {
    # Tratra Trust : réévaluation périodique des badges et des scores (la durée mini entre deux évaluations
    # d'un profil est configurable dans l'administration : TrustConfig.reevaluation_hours).
    'trust-reevaluate-profiles': {
        'task': 'trust.tasks.reevaluate_all_profiles',
        'schedule': 3600.0,
    },
}

# === DJSTRIPE ===
DJSTRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
DJSTRIPE_FOREIGN_KEY_TO_FIELD = 'id'

# Ancien secret partagé, accepté seulement en développement/test pour faciliter
# la transition. En production, configurez un secret par fournisseur ci-dessous.
PAYMENT_WEBHOOK_SECRET = config('PAYMENT_WEBHOOK_SECRET', default='')
# Secrets par fournisseur, requis pour leurs webhooks de production.
PAYMENT_OM_WEBHOOK_SECRET = config('PAYMENT_OM_WEBHOOK_SECRET', default='')
PAYMENT_MTN_WEBHOOK_SECRET = config('PAYMENT_MTN_WEBHOOK_SECRET', default='')
PAYMENT_CARD_WEBHOOK_SECRET = config('PAYMENT_CARD_WEBHOOK_SECRET', default='')

# === SENTRY ===
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    try:
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
            traces_sample_rate=float(config('SENTRY_TRACES_SAMPLE_RATE', default='0.1')),
            send_default_pii=env_bool('SENTRY_SEND_PII', False),
            auto_enabling_integrations=False,
            environment=config(
                'SENTRY_ENVIRONMENT',
                default='production' if os.getenv('DJANGO_ENV') == 'prod' else 'development',
            ),
        )
    except Exception as e:
        import logging

        logging.getLogger(__name__).warning("Sentry disabled: %s", e)

# === EMAIL ===
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_PORT = config('EMAIL_PORT')
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_BACKEND = config("EMAIL_BACKEND", default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config("EMAIL_HOST", default='')
EMAIL_PORT = int(config("EMAIL_PORT", default='587'))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
# EMAIL_USE_SSL = config("EMAIL_USE_SSL")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default='')
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default='')
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default='no-reply@tratra.invalid')

# === AXES ===
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # heure
AXES_LOCK_OUT_AT_FAILURE = True
AXES_ENABLE_ADMIN = True
AXES_VERBOSE = True
AXES_LOCKOUT_TEMPLATE = '403.html'  # Utilise un template custom si bloqué

# ENABLE_SSL_HARDENING = os.getenv("ENABLE_SSL_HARDENING", "true").lower() in ("1","true","yes")
#
# if ENABLE_SSL_HARDENING:
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
# else:
#     SECURE_HSTS_SECONDS = 0

# === OTHER ===
ACCOUNT_FORMS = {
    'signup': 'handy.forms.CustomSignupForm',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {  # 👈 ça c'est important
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': config('LOG_LEVEL', default='DEBUG' if DEBUG else 'INFO').upper(),
    },
}
