# settings/base.py
"""
Django settings for tratra project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

import channels
import environ
from decouple import config
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration

from tratra.settings import env

# env = environ.Env()
# environ.Env.read_env()
DEBUG = os.getenv("DEBUG", "False").lower() in ("1", "true", "yes")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
SECRET_KEY = config('SECRET_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-98yp&99d&^j57y15a7!*3h4+t#d2z0r@+e!@dy=e*_b(9m!47i'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = [
    "tratra.net",
    "www.tratra.net",
    "tratra.ci",
    "www.tratra.ci",
    "127.0.0.1",
    "localhost",
    "tratraweb",      # nom de service docker (utile pour tests internes)
]

# Pendant l’accès provisoire en HTTP sur :1934, ne force pas HTTPS

# CSRF (pas strictement nécessaire pour /admin en même origine, mais utile si tu postes depuis un front)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'handy',
    # Libs
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.linkedin',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    'axes',
    'django_celery_beat',
    'storages',
    'django_cleanup',
    'simple_history',
    'actstream',
    'channels',
    'push_notifications',
    'djstripe',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'tailwind',
    'theme',
    'grappelli',
    'import_export',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'django.contrib.humanize',

]
INSTALLED_APPS += ["corsheaders"]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # React dev
# ]
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'axes.middleware.AxesMiddleware',
    'handy.middleware.IPBlacklistMiddleware',

]

ROOT_URLCONF = 'tratra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tratra.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = 'handydash'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
# ACCOUNT_USERNAME_REQUIRED = False  # Ne pas exiger le champ username
# ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Auth via email uniquement
ACCOUNT_LOGIN_METHODS = {"email"}  # ou {"email","username"} selon ton besoin
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True  # Empêche les doublons

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # ✅ plus de SessionAuthentication
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

USE_I18N = True
TIME_ZONE = 'Africa/Abidjan'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
from decouple import config
import os

# ---------- STATIC & MEDIA ----------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

if DEBUG:
    # Assurez-vous que whitenoise est correctement configuré
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

    # Configuration pour servir les fichiers média en développement
    from django.conf.urls.static import static

    urlpatterns = [] + static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

MINIO_ENABLED = config('MINIO_ENABLED', default='1').lower() in ('1', 'true', 'yes')

if MINIO_ENABLED:
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},  # MEDIA → MinIO
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},  # STATIC → WhiteNoise
    }

    # Creds (AWS_* en priorité, sinon MINIO_ROOT_*)
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=config('MINIO_ROOT_USER', default='minioadmin'))
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=config('MINIO_ROOT_PASSWORD', default='minioadmin'))
    # public URL base (what .url will return)
    AWS_S3_CUSTOM_DOMAIN = "tratra.net"

    # path-style URLs (best for MinIO)

    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='tratra-media')
    AWS_S3_ENDPOINT_URL= config('AWS_S3_ENDPOINT_URL', default='http://minio:9000')  # service docker
    AWS_S3_REGION_NAME= config('AWS_S3_REGION_NAME', default='us-east-1')

    AWS_S3_ADDRESSING_STYLE= 'path'   # indispensable pour MinIO derrière Traefik/DNS
    AWS_S3_SIGNATURE_VERSION= 's3v4'
    AWS_S3_VERIFY= config('AWS_S3_VERIFY', default='0').lower() in ('1','true','yes')  # ← par défaut False si HTTP

    # URLs publiques non signées ? (utile si tu sers les médias directement via Nginx/Traefik)
    AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default='0').lower() in ('1','true','yes')

    # Optionnel si tu exposes MinIO publiquement sous un domaine :
    # AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None) or None
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},  # MEDIA → disque local
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }


WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'handy.User'  # Remplacez 'handy' par le nom de votre app

# === CHANNELS ===
ASGI_APPLICATION = 'tratra.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(config('REDIS_HOST', default='redis'), 6379)],
        },
    },
}

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']
# === CELERY ===
CELERY_BROKER_URL = config('REDIS_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_BEAT_SCHEDULE = {}

# === DJSTRIPE ===
DJSTRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')
DJSTRIPE_FOREIGN_KEY_TO_FIELD = 'id'

# === SENTRY ===
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration



try:
    sentry_sdk.init(
        dsn=config('SENTRY_DSN', default=''),
        integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True,
        auto_enabling_integrations=False,
    )
except Exception as e:
    import logging
    logging.getLogger(__name__).warning("Sentry disabled: %s", e)

# === EMAIL ===
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_PORT = config('EMAIL_PORT')
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = int(config("EMAIL_PORT"))
EMAIL_USE_TLS = config("EMAIL_USE_TLS")
# EMAIL_USE_SSL = config("EMAIL_USE_SSL")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# === AXES ===
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # heure
AXES_LOCK_OUT_AT_FAILURE = True
AXES_ENABLE_ADMIN = True
AXES_VERBOSE = True
AXES_LOCKOUT_TEMPLATE = '403.html'  # Utilise un template custom si bloqué

# ENABLE_SSL_HARDENING = os.getenv("ENABLE_SSL_HARDENING", "true").lower() in ("1","true","yes")
#
# if ENABLE_SSL_HARDENING:
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
# else:
#     SECURE_HSTS_SECONDS = 0

# === OTHER ===
ACCOUNT_FORMS = {
    'signup': 'handy.forms.CustomSignupForm',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {  # 👈 ça c'est important
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

