# Generated by Django 4.2.23 on 2026-10-10 01:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handy', '0033_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_sharing', models.BooleanField(default=False)),
                ('artisan_consent_at', models.DateTimeField(blank=True, null=True)),
                ('client_sharing', models.BooleanField(default=False)),
                ('client_consent_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('route_polyline', models.JSONField(blank=True, default=list)),
                ('route_eta_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('route_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('route_source', models.CharField(blank=True, default='', max_length=20)),
                ('route_updated_at', models.DateTimeField(blank=True, null=True)),
                ('route_origin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_session', to='handy.booking')),
            ],
        ),
        migrations.CreateModel(
            name='LivePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('artisan', 'Artisan'), ('client', 'Client')], max_length=10)),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='live.trackingsession')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['session', 'role', '-captured_at'], name='live_livepo_session_38a8b6_idx'), models.Index(fields=['received_at'], name='live_livepo_receive_b1506a_idx')],
            },
        ),
    ]
