# Generated by Django 4.2.23 on 2025-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0002_ipblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanprofile',
            name='cni_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='handymandocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('license', 'Permis de conduire'), ('casier', 'Casier Judiciaire'), ('insurance', 'Assurance'), ('certification', 'Certificats/diplomes'), ('other', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employeur', 'employeur'), ('handyman', 'Artisan'), ('admin', 'Administrateur')], default='client', max_length=20),
        ),
    ]
