# Generated by Django 4.2.23 on 2025-07-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0004_alter_notification_notification_type_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('employeur', 'employeur'), ('handyman', 'Artisan'), ('admin', 'Administrateur')], default='client', max_length=20, null=True),
        ),
    ]
