# Generated by Django 4.2.23 on 2025-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='handymanprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='handymen', to='handy.servicecategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
