# Generated by Django 4.2.23 on 2025-07-05 00:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0007_handymanprofile_commune_handymanprofile_quartier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Détails supplémentaires du devis ou conditions particulières', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('valid_until', models.DateField(blank=True, help_text="Date d'expiration du devis", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Permet de désactiver un devis sans le supprimer')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='handy.booking')),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'handyman')},
            },
        ),
    ]
