# Generated by Django 4.2.23 on 2025-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0009_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='handyman_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire du prestataire'),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix proposé'),
        ),
        migrations.AddField(
            model_name='booking',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
    ]
