# Generated by Django 4.2.23 on 2025-07-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0010_booking_handyman_comment_booking_proposed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='handy.booking'),
        ),
    ]
