# Generated by Django 4.2.23 on 2025-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0011_alter_conversation_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanprofile',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('profile_incomplete', 'Profil incomplet'), ('profile_completed', 'Profil complété'), ('booking_request', 'Demande de réservation'), ('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée'), ('payment_received', 'Paiement reçu'), ('review_received', 'Avis reçu'), ('message_received', 'Message reçu'), ('booking_status', 'Changement de statut de réservation')], max_length=50),
        ),
    ]
