# Generated by Django 4.2.23 on 2025-07-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0012_handymanprofile_deposit_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('deduction', 'Déduction mission')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Complété'), ('pending', 'En attente'), ('failed', 'Échoué')], default='completed', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction de caution',
                'verbose_name_plural': 'Transactions de cautions',
                'ordering': ['-date'],
            },
        ),
    ]
