# Generated by Django 4.2.23 on 2025-07-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0013_deposittransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handymanprofile',
            name='deposit_balance',
        ),
    ]
