# Generated by Django 4.2.23 on 2025-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0015_availabilityslot_bookingroute_bookingtimeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroute',
            name='eta_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='replacementsuggestion',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
