# Generated by Django 4.2.23 on 2025-10-17 14:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0016_alter_bookingroute_eta_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('gradient_start', models.CharField(default='#00B14F', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur hex valide attendue (#RRGGBB)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('gradient_end', models.CharField(default='#00D25F', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur hex valide attendue (#RRGGBB)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('cta_label', models.CharField(default='Découvrir', max_length=40)),
                ('cta_action', models.CharField(choices=[('open_services', 'Ouvrir la liste des services'), ('open_categories', 'Ouvrir la liste des catégories'), ('open_category', 'Ouvrir une catégorie précise'), ('open_artisans', 'Ouvrir la liste des artisans/populaires'), ('open_url', 'Ouvrir une URL externe')], default='open_services', max_length=30)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ordering', models.PositiveIntegerField(db_index=True, default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handy.servicecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Slide d'accueil",
                'verbose_name_plural': "Slides d'accueil",
                'ordering': ['ordering', '-id'],
                'indexes': [models.Index(fields=['is_active', 'ordering'], name='handy_heros_is_acti_8fabdd_idx'), models.Index(fields=['starts_at'], name='handy_heros_starts__2ebcfe_idx'), models.Index(fields=['ends_at'], name='handy_heros_ends_at_9163d1_idx')],
            },
        ),
    ]
