# Generated by Django 4.2.23 on 2026-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0017_service_image_url_alter_service_banner_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Carte'), ('transfer', 'Virement'), ('cash', 'Espèces'), ('check', 'Chèque'), ('om', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20),
        ),
    ]
