# Generated by Django 4.2.23 on 2026-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0018_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('held', 'Sous séquestre (escrow)'), ('released', "Versé à l'artisan"), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20),
        ),
    ]
