# Generated by Django 4.2.23 on 2026-06-21 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0019_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('refund_client', 'Remboursement client'), ('release_artisan', "Versement à l'artisan"), ('none', 'Aucune action')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('under_review', 'En examen'), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
