# Generated by Django 4.2.23 on 2026-06-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0020_booking_cancellation_fee_dispute_resolution_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymandocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20),
        ),
    ]
