# Generated by Django 4.2.23 on 2026-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0021_handymandocument_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementsuggestion',
            name='accepted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='replacementsuggestion',
            constraint=models.UniqueConstraint(fields=('booking', 'suggested_service'), name='uniq_replacement_per_service'),
        ),
    ]
