# Generated by Django 4.2.23 on 2026-10-04

import handy.models
import handy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0026_seed_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymandocument',
            name='file',
            field=models.FileField(
                storage=handy.storage.KycPrivateStorage(),
                upload_to=handy.models.private_kyc_upload_path,
            ),
        ),
    ]
