# Generated by Django 4.2.23 on 2026-10-08 18:26
"""L1a (§6.1) : PROTECT sur les relations porteuses d'historique.

Supprimer un compte, une réservation ou un profil ne doit plus effacer en cascade
réservations, paiements, versements, dépôts, factures, abonnements, avis, litiges,
compte de versement ni documents KYC. `on_delete` est un attribut Python (non-DB)
de Django 4.2 : cette migration ne modifie QUE l'état (sqlmigrate : no-op partout),
elle est réversible sans perte et sans verrou.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0028_clean_business_plan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handyman_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='handy.booking'),
        ),
        migrations.AlterField(
            model_name='handymandocument',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='handy.handymanprofile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='handy.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='handy.booking'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='handyman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='handy.booking'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
