# Generated by Django 4.2.23 on 2026-10-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0029_protect_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Inscription'), ('login', 'Connexion'), ('phone', 'Vérification téléphone'), ('recovery', 'Récupération du compte')], default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
