# Generated by Django 4.2.23 on 2026-10-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0031_review_criteria_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymandocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_documents', to='handy.servicecategory'),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='handymandocument',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='trust_badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='trust_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='trust_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
