# Generated by Django 4.2.23 on 2026-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0032_trust_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('profile_incomplete', 'Profil incomplet'), ('profile_completed', 'Profil complété'), ('booking_request', 'Demande de réservation'), ('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée'), ('payment_received', 'Paiement reçu'), ('review_received', 'Avis reçu'), ('review_reply', 'Réponse à un avis'), ('message_received', 'Message reçu'), ('booking_status', 'Changement de statut de réservation'), ('live_en_route', 'Artisan en route'), ('live_arrived', 'Artisan arrivé')], db_index=True, max_length=50),
        ),
    ]
